# Stage 1: Build React App
FROM node:16 as build

WORKDIR /app
COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm install
COPY ./frontend ./
RUN npm run build

# Stage 2: Serve React App with Nginx
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

# Экспонируем порт для доступа к приложению
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
